service: paywall-calculator

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin
  # - serverless-plugin-warmup

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 35
  vpc:
    securityGroupIds:
      - 'sg-a329daeb'
    subnetIds:
      - 'subnet-01d9614b'
      - 'subnet-57a35579'
      - 'subnet-47ea1020'

package:
  individually: true

functions:
  lambda:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}

custom:
  serverless-offline:
    httpPort: 4000
    httpApi:
      - path: